fullnameOverride: "c7n-prometheus"

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - {{altermanagerAccesssMode}}
          resources:
            requests:
              storage: {{altermanagerStorage}}
          # 通过 seletor 选择绑定的 pv
          selector:
            matchLabels:
              choerodon.io/name: {{alertmanager-pv}}

grafana:
  adminPassword: "{{adminPassword}}"
  ingress:
    enabled: true
    hosts:
      - {{host}}
    tls:
      - secretName: tls-grafana-nginx
        hosts:
          - {{host}}
    annotations:
      kubernetes.io/ingress.class: "nginx"
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
      # iframe 嵌套跨域
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "X-Frame-Options: ALLOW-ALL";
  persistence:
    enabled: true
    accessModes:
      - {{grafanaAccessMode}}
    size: {{grafanaStorage}}
    existingClaim: c7n-grafana-pvc
    # 选择 PVC 绑定的 PV
    selector:
      matchLabels:
        choerodon.io/name: {{grafana-pv}}
  grafana.ini:
    paths:
      data: /var/lib/grafana/data
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    analytics:
      check_for_updates: true
    log:
      mode: console
    grafana_net:
      url: https://grafana.net
    server:
      root_url: http://{{host}}
    auth.generic_oauth:
      name: Choerodon
      enabled: true
      allow_sign_up: true
      client_id: {{grafana-client-id}}
      client_secret: grafana
      scopes: default
      auth_url: {{api-host}}/oauth/oauth/authorize
      token_url: {{api-host}}/oauth/oauth/token
      api_url: {{api-host}}/base/v1/users/self
      team_ids:
      allowed_organizations:

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - {{prometheusAccessMode}}
          resources:
            requests:
              storage: {{prometheusStorage}}
          # 通过 seletor 选择绑定的 pv
          selector:
            matchLabels:
              choerodon.io/name: {{prometheus-pv}}